
export const colleges = [
    "A.P. Shah Institute of Technology, Thane",
    "Acharya Institute of Technology, Bangalore",
    "Adani Institute of Infrastructure Management, Ahmedabad",
    "Aditya Institute of Technology and Management, Tekkali",
    "Ajeenkya DY Patil University, Pune",
    "Aligarh Muslim University, Aligarh",
    "All India Institute of Medical Sciences, New Delhi",
    "Alliance University, Bangalore",
    "Amity University, Noida",
    "Amrita Vishwa Vidyapeetham, Coimbatore",
    "Anand Institute of Higher Technology, Chennai",
    "Andhra University College of Engineering, Visakhapatnam",
    "Anil Neerukonda Institute of Technology and Sciences, Visakhapatnam",
    "Anna University, Chennai",
    "Ansal University, Gurgaon",
    "Apeejay Stya University, Gurgaon",
    "Ashoka University, Sonipat",
    "Assam Don Bosco University, Guwahati",
    "Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Gwalior",
    "Aurora's Engineering College, Hyderabad",
    "Azim Premji University, Bengaluru",
    "B.M.S. College of Engineering, Bangalore",
    "Babasaheb Bhimrao Ambedkar University, Lucknow",
    "Banaras Hindu University, Varanasi",
    "Banasthali Vidyapith, Banasthali",
    "Bangalore Institute of Technology, Bangalore",
    "Bennett University, Greater Noida",
    "Bhagalpur College of Engineering, Bhagalpur",
    "Bharati Vidyapeeth Deemed University College of Engineering, Pune",
    "Birla Institute of Technology and Science, Pilani",
    "Birla Institute of Technology, Mesra",
    "BITT Polytechnic, Ranchi",
    "BML Munjal University, Gurgaon",
    "BMS Institute of Technology and Management, Bangalore",
    "BRACT'S Vishwakarma Institute of Information Technology, Pune",
    "Brainware University, Kolkata",
    "C. V. Raman College of Engineering, Bhubaneswar",
    "Cambridge Institute of Technology, Bangalore",
    "Chandigarh University, Mohali",
    "Chaitanya Bharathi Institute of Technology, Hyderabad",
    "Chalapathi Institute of Engineering and Technology, Guntur",
    "Chandigarh College of Engineering and Technology, Chandigarh",
    "Chandigarh Group of Colleges, Landran",
    "Chitkara University, Punjab",
    "Christ University, Bangalore",
    "Christian Medical College, Vellore",
    "Cochin University of Science and Technology, Kochi",
    "Coimbatore Institute of Technology, Coimbatore",
    "College of Engineering, Pune",
    "Cummins College of Engineering for Women, Pune",
    "D. Y. Patil College of Engineering, Pune",
    "D.K.T.E. Society's Textile and Engineering Institute, Ichalkaranji",
    "Dayalbagh Educational Institute, Agra",
    "Dayananda Sagar College of Engineering, Bangalore",
    "Deenbandhu Chhotu Ram University of Science and Technology, Murthal",
    "Delhi Technological University, Delhi",
    "Devi Ahilya Vishwavidyalaya, Indore",
    "Dharmsinh Desai University, Nadiad",
    "Dhirubhai Ambani Institute of Information and Communication Technology, Gandhinagar",
    "Don Bosco Institute of Technology, Mumbai",
    "Dr. B. R. Ambedkar National Institute of Technology, Jalandhar",
    "Dr. Babasaheb Ambedkar Technological University, Lonere",
    "Dr. D. Y. Patil Institute of Technology, Pune",
    "Dwarkadas J. Sanghvi College of Engineering, Mumbai",
    "Faculty of Management Studies, University of Delhi",
    "Fergusson College, Pune",
    "FLAME University, Pune",
    "FORE School of Management, New Delhi",
    "Fr. Conceicao Rodrigues College of Engineering, Mumbai",
    "G. H. Patel College of Engineering & Technology, Vallabh Vidyanagar",
    "G. Narayanamma Institute of Technology and Science, Hyderabad",
    "Galgotias University, Greater Noida",
    "Gandhi Institute of Technology and Management (GITAM), Visakhapatnam",
    "Ganpat University, Mehsana",
    "Gauhati University, Guwahati",
    "Gayatri Vidya Parishad College of Engineering, Visakhapatnam",
    "GMR Institute of Technology, Rajam",
    "Goa University, Goa",
    "Gokaraju Rangaraju Institute of Engineering and Technology, Hyderabad",
    "Government College of Engineering, Amravati",
    "Government College of Engineering, Aurangabad",
    "Government College of Engineering, Karad",
    "Government College of Technology, Coimbatore",
    "Govind Ballabh Pant University of Agriculture and Technology, Pantnagar",
    "Graphic Era University, Dehradun",
    "Great Lakes Institute of Management, Chennai",
    "Gujarat Technological University, Ahmedabad",
    "Guru Ghasidas Vishwavidyalaya, Bilaspur",
    "Guru Gobind Singh Indraprastha University, Delhi",
    "Guru Jambheshwar University of Science and Technology, Hisar",
    "Guru Nanak Dev University, Amritsar",
    "Gurukula Kangri Vishwavidyalaya, Haridwar",
    "Haldia Institute of Technology, Haldia",
    "Harcourt Butler Technical University, Kanpur",
    "Hemwati Nandan Bahuguna Garhwal University, Srinagar",
    "Heritage Institute of Technology, Kolkata",
    "Himachal Pradesh University, Shimla",
    "Hindu College, Delhi",
    "Hindustan Institute of Technology and Science, Chennai",
    "I. K. Gujral Punjab Technical University, Jalandhar",
    "ICFAI Foundation for Higher Education, Hyderabad",
    "IIIT Hyderabad",
    "IIMT University, Meerut",
    "IMS Engineering College, Ghaziabad",
    "Indian Agricultural Research Institute, New Delhi",
    "Indian Institute of Engineering Science and Technology, Shibpur",
    "Indian Institute of Foreign Trade, New Delhi",
    "Indian Institute of Information Technology, Allahabad",
    "Indian Institute of Information Technology, Design and Manufacturing, Jabalpur",
    "Indian Institute of Information Technology, Kottayam",
    "Indian Institute of Management, Ahmedabad",
    "Indian Institute of Management, Bangalore",
    "Indian Institute of Management, Calcutta",
    "Indian Institute of Management, Indore",
    "Indian Institute of Management, Kashipur",
    "Indian Institute of Management, Kozhikode",
    "Indian Institute of Management, Lucknow",
    "Indian Institute of Management, Raipur",
    "Indian Institute of Management, Rohtak",
    "Indian Institute of Management, Shillong",
    "Indian Institute of Management, Tiruchirappalli",
    "Indian Institute of Management, Udaipur",
    "Indian Institute of Science Education and Research, Bhopal",
    "Indian Institute of Science Education and Research, Kolkata",
    "Indian Institute of Science Education and Research, Mohali",
    "Indian Institute of Science Education and Research, Pune",
    "Indian Institute of Science Education and Research, Thiruvananthapuram",
    "Indian Institute of Science, Bangalore",
    "Indian Institute of Space Science and Technology, Thiruvananthapuram",
    "Indian Institute of Technology (BHU), Varanasi",
    "Indian Institute of Technology, Bhubaneswar",
    "Indian Institute of Technology, Bombay",
    "Indian Institute of Technology, Delhi",
    "Indian Institute of Technology, Gandhinagar",
    "Indian Institute of Technology, Guwahati",
    "Indian Institute of Technology, Hyderabad",
    "Indian Institute of Technology, Indore",
    "Indian Institute of Technology, Jodhpur",
    "Indian Institute of Technology, Kanpur",
    "Indian Institute of Technology, Kharagpur",
    "Indian Institute of Technology, Madras",
    "Indian Institute of Technology, Mandi",
    "Indian Institute of Technology, Palakkad",
    "Indian Institute of Technology, Patna",
    "Indian Institute of Technology, Roorkee",
    "Indian Institute of Technology, Ropar",
    "Indian Institute of Technology, Tirupati",
    "Indian Institute of Technology, Varanasi (BHU)",
    "Indian Maritime University, Chennai",
    "Indian School of Mines, Dhanbad",
    "Indira Gandhi Delhi Technical University for Women, Delhi",
    "Indira Gandhi National Open University, New Delhi",
    "Indraprastha Institute of Information Technology, Delhi",
    "Institute of Aeronautical Engineering, Hyderabad",
    "Institute of Chemical Technology, Mumbai",
    "Institute of Engineering and Management, Kolkata",
    "Institute of Management Technology, Ghaziabad",
    "Integral University, Lucknow",
    "International Institute of Information Technology, Bangalore",
    "International Management Institute, New Delhi",
    "J.C. Bose University of Science and Technology, YMCA, Faridabad",
    "Jadavpur University, Kolkata",
    "Jagran Lakecity University, Bhopal",
    "Jai Hind College, Mumbai",
    "Jain University, Bangalore",
    "Jamia Hamdard, New Delhi",
    "Jamia Millia Islamia, New Delhi",
    "Jawaharlal Nehru Centre for Advanced Scientific Research, Bangalore",
    "Jawaharlal Nehru Technological University, Anantapur",
    "Jawaharlal Nehru Technological University, Hyderabad",
    "Jawaharlal Nehru Technological University, Kakinada",
    "Jawaharlal Nehru University, New Delhi",
    "Jaypee Institute of Information Technology, Noida",
    "Jaypee University of Engineering and Technology, Guna",
    "JIS College of Engineering, Kalyani",
    "JK Lakshmipat University, Jaipur",
    "JSS Academy of Technical Education, Bangalore",
    "JSS Science and Technology University, Mysore",
    "K L University, Guntur",
    "K. J. Somaiya College of Engineering, Mumbai",
    "Kakatiya Institute of Technology and Science, Warangal",
    "Kakatiya University, Warangal",
    "Kalasalingam Academy of Research and Education, Srivilliputhur",
    "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
    "Koneru Lakshmaiah Education Foundation, Vaddeswaram",
    "Kongu Engineering College, Erode",
    "Karunya Institute of Technology and Sciences, Coimbatore",
    "Kaziranga University, Jorhat",
    "KCG College of Technology, Chennai",
    "KLE Technological University, Hubli",
    "Koneru Lakshmaiah Education Foundation, Guntur",
    "Krishna Institute of Engineering and Technology, Ghaziabad",
    "Kumaraguru College of Technology, Coimbatore",
    "Kurukshetra University, Kurukshetra",
    "L. D. College of Engineering, Ahmedabad",
    "Lady Shri Ram College for Women, New Delhi",
    "Lakshmi Narain College of Technology, Bhopal",
    "LNM Institute of Information Technology, Jaipur",
    "Lovely Professional University, Jalandhar",
    "Loyola College, Chennai",
    "M. S. Ramaiah Institute of Technology, Bangalore",
    "Madan Mohan Malaviya University of Technology, Gorakhpur",
    "Madras Christian College, Chennai",
    "Madras Institute of Technology, Chennai",
    "Madurai Kamaraj University, Madurai",
    "Maharaja Agrasen Institute of Technology, Delhi",
    "Maharaja Sayajirao University of Baroda, Vadodara",
    "Maharishi Markandeshwar University, Mullana",
    "Mahatma Gandhi Institute of Technology, Hyderabad",
    "Mahatma Jyotiba Phule Rohilkhand University, Bareilly",
    "Malaviya National Institute of Technology, Jaipur",
    "Manav Rachna International University, Faridabad",
    "Mangalore University, Mangalore",
    "Manipal Academy of Higher Education, Manipal",
    "Manipal University, Jaipur",
    "Maulana Abul Kalam Azad University of Technology, Kolkata",
    "Maulana Azad National Institute of Technology, Bhopal",
    "Maulana Azad National Urdu University, Hyderabad",
    "Medi-Caps University, Indore",
    "Meerut Institute of Engineering and Technology, Meerut",
    "Mepco Schlenk Engineering College, Sivakasi",
    "Miranda House, Delhi",
    "MIT Art, Design and Technology University, Pune",
    "MIT World Peace University, Pune",
    "Mizoram University, Aizawl",
    "Motilal Nehru National Institute of Technology, Allahabad",
    "Mount Carmel College, Bangalore",
    "Nagaland University, Lumami",
    "NALSAR University of Law, Hyderabad",
    "Narsee Monjee Institute of Management Studies, Mumbai",
    "National Fire Service College, Nagpur",
    "National Institute of Construction Management and Research, Pune",
    "National Institute of Design, Ahmedabad",
    "National Institute of Engineering, Mysore",
    "National Institute of Food Technology Entrepreneurship and Management, Sonipat",
    "National Institute of Industrial Engineering, Mumbai",
    "National Institute of Technology, Agartala",
    "National Institute of Technology, Andhra Pradesh",
    "National Institute of Technology, Arunachal Pradesh",
    "National Institute of Technology, Calicut",
    "National Institute of Technology, Delhi",
    "National Institute of Technology, Durgapur",
    "National Institute of Technology, Goa",
    "National Institute of Technology, Hamirpur",
    "National Institute of Technology, Jamshedpur",
    "National Institute of Technology, Karnataka",
    "National Institute of Technology, Kurukshetra",
    "National Institute of Technology, Manipur",
    "National Institute of Technology, Meghalaya",
    "National Institute of Technology, Mizoram",
    "National Institute of Technology, Nagaland",
    "National Institute of Technology, Patna",
    "National Institute of Technology, Puducherry",
    "National Institute of Technology, Raipur",
    "National Institute of Technology, Rourkela",
    "National Institute of Technology, Sikkim",
    "National Institute of Technology, Silchar",
    "National Institute of Technology, Srinagar",
    "National Institute of Technology, Surat",
    "National Institute of Technology, Tiruchirappalli",
    "National Institute of Technology, Uttarakhand",
    "National Institute of Technology, Warangal",
    "National Law School of India University, Bangalore",
    "Netaji Subhas University of Technology, Delhi",
    "NIIT University, Neemrana",
    "Nirma University, Ahmedabad",
    "NITTE Meenakshi Institute of Technology, Bangalore",
    "Nizam's Institute of Medical Sciences, Hyderabad",
    "North-Eastern Hill University, Shillong",
    "O.P. Jindal Global University, Sonipat",
    "Osmania University, Hyderabad",
    "P.E.S. College of Engineering, Mandya",
    "PES University, Bangalore",
    "PSG College of Technology, Coimbatore",
    "Pandit Deendayal Energy University, Gandhinagar",
    "Pandit Dwarka Prasad Mishra Indian Institute of Information Technology, Design and Manufacturing, Jabalpur",
    "Panjab University, Chandigarh",
    "Parul University, Vadodara",
    "Patna University, Patna",
    "PCCOE - Pimpri Chinchwad College of Engineering, Pune",
    "PEC University of Technology, Chandigarh",
    "Periyar University, Salem",
    "Pondicherry University, Puducherry",
    "Post Graduate Institute of Medical Education and Research, Chandigarh",
    "Pranveer Singh Institute of Technology, Kanpur",
    "Presidency College, Chennai",
    "Presidency University, Bangalore",
    "Presidency University, Kolkata",
    "PSG College of Arts and Science, Coimbatore",
    "Punjab Agricultural University, Ludhiana",
    "Punjab Engineering College, Chandigarh",
    "Punjabi University, Patiala",
    "Quantum University, Roorkee",
    "R. V. College of Engineering, Bangalore",
    "Rabindra Bharati University, Kolkata",
    "Raffles University, Neemrana",
    "Rajalakshmi Engineering College, Chennai",
    "Rajasthan Technical University, Kota",
    "Rajiv Gandhi Institute of Petroleum Technology, Amethi",
    "Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal",
    "Rajiv Gandhi University of Health Sciences, Bangalore",
    "Rajiv Gandhi University, Itanagar",
    "Ramakrishna Mission Vivekananda Educational and Research Institute, Belur",
    "Ramdeobaba College of Engineering and Management, Nagpur",
    "Ramjas College, Delhi",
    "Ranchi University, Ranchi",
    "Rashtrasant Tukadoji Maharaj Nagpur University, Nagpur",
    "Rashtriya Raksha University, Gandhinagar",
    "Ravenshaw University, Cuttack",
    "REVA University, Bangalore",
    "Royal Global University, Guwahati",
    "S. P. Jain Institute of Management and Research, Mumbai",
    "SASTRA University, Thanjavur",
    "SVKM's Narsee Monjee Institute of Management Studies, Mumbai",
    "Sambalpur University, Sambalpur",
    "Sanjay Ghodawat University, Kolhapur",
    "Sant Longowal Institute of Engineering and Technology, Longowal",
    "Sardar Patel College of Engineering, Mumbai",
    "Sardar Vallabhbhai National Institute of Technology, Surat",
    "Sardar Vallabhbhai Patel University of Agriculture and Technology, Meerut",
    "Sathyabama Institute of Science and Technology, Chennai",
    "Saveetha Institute of Medical and Technical Sciences, Chennai",
    "Savitribai Phule Pune University, Pune",
    "School of Planning and Architecture, Bhopal",
    "School of Planning and Architecture, Delhi",
    "School of Planning and Architecture, Vijayawada",
    "Sharda University, Greater Noida",
    "Shiv Nadar University, Greater Noida",
    "Shoolini University of Biotechnology and Management Sciences, Solan",
    "Shri Mata Vaishno Devi University, Katra",
    "Shri Ram College of Commerce, Delhi",
    "Shri Ramdeobaba College of Engineering and Management, Nagpur",
    "Shri Vile Parle Kelavani Mandal's Dwarkadas J. Sanghvi College of Engineering, Mumbai",
    "Siddaganga Institute of Technology, Tumkur",
    "Sikkim Manipal University, Gangtok",
    "Silicon Institute of Technology, Bhubaneswar",
    "Sister Nivedita University, Kolkata",
    "SOA University, Bhubaneswar",
    "Sona College of Technology, Salem",
    "SRM Institute of Science and Technology, Chennai",
    "St. Joseph's College, Bangalore",
    "St. Stephen's College, Delhi",
    "St. Xavier's College, Ahmedabad",
    "St. Xavier's College, Kolkata",
    "St. Xavier's College, Mumbai",
    "Symbiosis Institute of Business Management, Pune",
    "Symbiosis International University, Pune",
    "Tamil Nadu Agricultural University, Coimbatore",
    "Tata Institute of Fundamental Research, Mumbai",
    "Tata Institute of Social Sciences, Mumbai",
    "Tezpur University, Tezpur",
    "Thadomal Shahani Engineering College, Mumbai",
    "Thapar Institute of Engineering and Technology, Patiala",
    "The LNM Institute of Information Technology, Jaipur",
    "The National Law Institute University, Bhopal",
    "The West Bengal National University of Juridical Sciences, Kolkata",
    "Thiagarajar College of Engineering, Madurai",
    "Tripura University, Agartala",
    "Unitedworld Institute of Design, Gandhinagar",
    "University of Allahabad, Allahabad",
    "University of Calcutta, Kolkata",
    "University of Calicut, Calicut",
    "University of Delhi, Delhi",
    "University of Hyderabad, Hyderabad",
    "University of Jammu, Jammu",
    "University of Kashmir, Srinagar",
    "University of Kerala, Thiruvananthapuram",
    "University of Kota, Kota",
    "University of Lucknow, Lucknow",
    "University of Madras, Chennai",
    "University of Mumbai, Mumbai",
    "University of Mysore, Mysore",
    "University of North Bengal, Siliguri",
    "University of Petroleum and Energy Studies (UPES), Dehradun",
    "University of Rajasthan, Jaipur",
    "University School of Information, Communication and Technology, Delhi",
    "Utkal University, Bhubaneswar",
    "Uttaranchal University, Dehradun",
    "V.J.T.I. Mumbai",
    "Vardhaman College of Engineering, Hyderabad",
    "Vasavi College of Engineering, Hyderabad",
    "Veer Surendra Sai University of Technology, Burla",
    "Veermata Jijabai Technological Institute, Mumbai",
    "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology, Chennai",
    "Vellore Institute of Technology, Vellore",
    "Vellore Institute of Technology, Amaravati",
    "Vellore Institute of Technology, Bhopal",
    "Vellore Institute of Technology, Chennai",
    "Vidya Jyothi Institute of Technology, Hyderabad",
    "Vidyalankar Institute of Technology, Mumbai",
    "Vignan's Foundation for Science, Technology and Research, Guntur",
    "Vikram Sarabhai Space Centre, Thiruvananthapuram",
    "Vinayaka Missions Research Foundation, Salem",
    "Visvesvaraya National Institute of Technology, Nagpur",
    "Visvesvaraya Technological University, Belgaum",
    "VNR Vignana Jyothi Institute of Engineering and Technology, Hyderabad",
    "Walchand College of Engineering, Sangli",
    "West Bengal State University, Barasat",
    "Xavier Institute of Management, Bhubaneswar",
    "Xavier Labour Relations Institute (XLRI), Jamshedpur",
    "Xavier University, Bhubaneswar",
    "Yeshwantrao Chavan College of Engineering, Nagpur"
];
