
export const courses = [
    { value: 'btech-cs', label: 'B.Tech in Computer Science' },
    { value: 'btech-mech', label: 'B.Tech in Mechanical Engineering' },
    { value: 'btech-elec', label: 'B.Tech in Electrical Engineering' },
    { value: 'btech-civil', label: 'B.Tech in Civil Engineering' },
    { value: 'btech-it', label: 'B.Tech in Information Technology' },
    { value: 'btech-ece', label: 'B.Tech in Electronics & Communication' },
    { value: 'btech-chem', label: 'B.Tech in Chemical Engineering' },
    { value: 'btech-aero', label: 'B.Tech in Aerospace Engineering' },
    { value: 'btech-biotech', label: 'B.Tech in Biotechnology' },
    { value: 'bba', label: 'Bachelor of Business Administration' },
    { value: 'bms', label: 'Bachelor of Management Studies' },
    { value: 'bcom', label: 'Bachelor of Commerce' },
    { value: 'bca', label: 'Bachelor of Computer Applications' },
    { value: 'ba-eng', label: 'B.A. in English Literature' },
    { value: 'ba-hist', label: 'B.A. in History' },
    { value: 'ba-econ', label: 'B.A. in Economics' },
    { value: 'ba-polsci', label: 'B.A. in Political Science' },
    { value: 'ba-soc', label: 'B.A. in Sociology' },
    { value: 'ba-psy', label: 'B.A. in Psychology' },
    { value: 'ba-jour', label: 'B.A. in Journalism & Mass Communication' },
    { value: 'bsc-phy', label: 'B.Sc. in Physics' },
    { value: 'bsc-chem', label: 'B.Sc. in Chemistry' },
    { value: 'bsc-math', label: 'B.Sc. in Mathematics' },
    { value: 'bsc-bio', label: 'B.Sc. in Biology' },
    { value: 'bsc-biotech', label: 'B.Sc. in Biotechnology' },
    { value: 'bsc-cs', label: 'B.Sc. in Computer Science' },
    { value: 'llb', label: 'Bachelor of Laws (LLB)' },
    { value: 'ba-llb', label: 'B.A. LLB (Honours)' },
    { value: 'bpharma', label: 'Bachelor of Pharmacy' },
    { value: 'bds', label: 'Bachelor of Dental Surgery' },
    { value: 'mbbs', label: 'Bachelor of Medicine, Bachelor of Surgery' },
    { value: 'bhm', label: 'Bachelor of Hotel Management' },
    { value: 'bdes', label: 'Bachelor of Design' },
    { value: 'mba', label: 'Master of Business Administration' },
    { value: 'mtech-cs', label: 'M.Tech in Computer Science' },
    { value: 'mca', label: 'Master of Computer Applications' },
    { value: 'mcom', label: 'Master of Commerce' },
    { value: 'ma-eng', label: 'M.A. in English Literature' },
    { value: 'ma-econ', label: 'M.A. in Economics' },
    { value: 'msc-phy', label: 'M.Sc. in Physics' },
    { value: 'phd-phy', label: 'PhD in Physics' },
    { value: 'other', label: 'Other' },
];
